apiVersion: apps/v1
kind: Deployment
metadata:
  name: 21i-1103_frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend1
  template:
    metadata:
      labels:
        app: frontend1
    spec:
      containers:
      - name:  frontend
        image: samiirshad1103343/scd-final-lab-exam-31304-master-21i-1103_frontend:latest
      nodeSelector:
        kubernetes.io/hostname: kind-worker
